import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layouts/NavBar";

const inter = Inter({ subsets: ["latin"] });

// index.html => head tag
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// <App/>
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <App /> */}
        <NavBar/>
        {children} 
      </body>
    </html>
  );
}
